import type { Metadata } from "next";
import localFont from "next/font/local";
import Navbar from "./components/navbar/index";
import "./globals.css";
import Footer from "./components/footer/index";
import Link from "next/link";
import { FaWhatsapp } from "react-icons/fa"; // Import FaWhatsapp icon
import { ToastContainer } from "react-toastify"; // Import ToastContainer
import "react-toastify/dist/ReactToastify.css"; // Import Toastify CSS

// Import fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const whatsappNumber = "923084401935";
  const message = "Hello, I would like to get in touch!";

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="fixed bottom-4 right-4 z-50 group">
          <Link
            href={`https://wa.me/${whatsappNumber}?text=${encodeURIComponent(message)}`}
            target="_blank"
            rel="noopener noreferrer"
            aria-label="WhatsApp"
          >
            <FaWhatsapp className="text-green-500 h-14 w-14 sm:text-3xl transition duration-300 hover:animate-shake" />
          </Link>
          <span className="absolute left-1/2 transform -translate-x-1/2 bottom-16 bg-zinc-200 text-black text-sm py-1 px-2 rounded opacity-0 group-hover:opacity-100 transition-opacity duration-200">
            How can I help you?
          </span>
        </div>

        <div className="flex flex-col w-full h-full">
          {/* Navbar: fixed at the top */}
          <div className="h-fit fixed w-full flex flex-row z-50 justify-center item-center">
            <Navbar />
          </div>

          {/* ToastContainer for global toast notifications */}
          <ToastContainer
            position="top-right"
            autoClose={5000} // Auto-close after 5 seconds
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
          />

          {/* Content below Navbar */}
          <div className="flex flex-col h-full m-0 "> {/* Increased top margin for fixed navbar and added horizontal padding */}
            {children}
          </div>

          <div className="h-fit w-full">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
